version: "3.5"

services:
  postgres:
    container_name: postgres-db
    image: postgres:13.2-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - postgres
    networks:
      - data
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - $SMTP_PORT:1025
      - $MAILHOG_CLIENT_PORT:8025
    networks:
      - data

  minio:
    build:
      context: ./src/storage/minio
      dockerfile: Dockerfile
    container_name: minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=$STORAGE_ACCESS
      - MINIO_SECRET_KEY=$STORAGE_SECRET
    entrypoint: sh
    command: -c 'mkdir -p /export/$PUBLIC_BUCKET && mkdir -p /export/$PRIVATE_BUCKET
      \ && mkdir -p /export/$TEMPORARY_BUCKET && /usr/bin/minio server --address
      :9000 /export'

networks:
  data: null
