name: Krater CI Pipeline

on:
  push: 
    paths:
      - 'src/modules/{{MODULE}}/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Go to {{MODULE}}
        run: cd ./src/modules/{{MODULE}}
      - uses: actions/cache@v2
        with:
          path: 'src/**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('src/**/package-lock.json') }
      - name: Install packages
        if: steps.npm-cache.outputs.cache-hit ! 'true'
        run: npm install
      - name: Run Lint
        run: npm run lint